### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by jesmitty** [amymcgovern/pyparrot#9]
I thought I'd start slow and just ran python findMambo.py

got "
Traceback (most recent call last):
  File "findMambo.py", line 16, in <module>
    class ScanDelegate(DefaultDelegate):
NameError: name 'DefaultDelegate' is not defined
"

Is there something else I should be doing

**Comment by amymcgovern** [comment]
The top of the file does a conditional import:

try:
    from bluepy.btle import Scanner, DefaultDelegate
    BLEAvailable = True
except:
    BLEAvailable = False

This means it only works if BLEAvailable is true.  So my assumption is you are not on Linux (which findMambo requires, since the BLE package only works on linux right now).  If you have a recent mambo with a camera, you can use that on any OS as it uses wifi.

**Comment by jesmitty** [comment]
Thank you.
